services:
  rewards-api:
    build:
      context: .
      dockerfile: ./Dockerfile.Api
    image: ada-rewards-reporter/api:latest
    container_name: rewards-api
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - "${USERPROFILE}\\.aspnet\\https:/https/"